---

apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-sql
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=false
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: xpkg.upbound.io/devops-toolkit/dot-sql:v0.8.2
